# This is a basic workflow to help you get started with Actions

name: Release CRPlugin

# Controls when the action will run. 
on:
  # Triggers the workflow on push with version tag
  push:
    tags:
      - 'v*.*.*'  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      plugin-name: StoryArcFromTitles
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      # Runs a set of commands using the runners shell
      - name: Build
        run: |
          zip -r ${{ plugin-name }}-${{ steps.get_version.outputs.VERSION }}.crplugin * -x "*.git*" *.md      

      # Runs a set of commands using the runners shell
      - name: Test
        run: |
          unzip -vl ${{ plugin-name }}-${{ steps.get_version.outputs.VERSION }}.crplugin
          echo ${{ github.workflow }}
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ plugin-name }}-${{ steps.get_version.outputs.VERSION }}.crplugin
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}         
          
